name: Create a daily release
on:
  schedule:
    - cron: '0 2 * * *' # Scheduled runs every day at 2am UTC
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - run: |
          gh release create "${{ steps.date.outputs.date }}a" --title "${{ steps.date.outputs.date }}a armbian-next auto daily build" --notes "auto daily build" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_ARMBIAN_RELEASE }}
