name: master-latest

on:
  push:
    branches: [ main ]
  #schedule:
  #  - cron: '0 3 * * *' # Scheduled runs every day at 3am UTC

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'rpardini' }}
    steps:

      - name: Checkout build repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/armbian-build
          ref: extensions # branch to build from.
          clean: true # true is default. it *will* delete the hosts /dev if mounted inside.
          path: "" # use default path

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # github username or org
          password: ${{ secrets.GITHUB_TOKEN }}    # github actions builtin token. repo has to have pkg access.

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Generate Dockerfile via Armbian helper script
        id: generate
        run: |
          DOCKERFILE_GENERATE_ONLY=yes bash ./docker.sh

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64 #,linux/arm64
          pull: true # Pull new version of base image, always; avoid bit-rot
          push: true
          labels: |
            org.opencontainers.image.title=${{ github.repository }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
          cache-from: type=gha # all-automatic Github Actions caching
          cache-to: type=gha,mode=max
          #build-args: |
          #  UPSTREAM_VERSION=${{env.UPSTREAM_VERSION}}
          #  UPSTREAM_BRANCH=${{env.UPSTREAM_VERSION}}
          tags: ghcr.io/${{ github.repository }}:armbian-next-latest

