name: packages-simple

on:
  schedule:
    - cron: '0 1 * * *' # Scheduled runs every day at 1am UTC
  workflow_dispatch:
  workflow_call:


jobs:

  "Packages":
    if: ${{ github.repository_owner == 'rpardini' }}
    runs-on: ubuntu-latest
    name: "Packages"
    env:
      OCI_TARGET_BASE: "ghcr.io/${{ github.repository }}/" # This is picked up by the Docker launcher automatically
      DOCKER_ARMBIAN_BASE_COORDINATE_PREFIX: "ghcr.io/${{ github.repository }}:armbian-next-" # Use Docker image in same repo
      DOCKER_SKIP_UPDATE: "yes" # Do not apt update/install/requirements/etc during Dockerfile build, trust DOCKER_ARMBIAN_BASE_COORDINATE_PREFIX's images are up-to-date

    steps:

      # Login to ghcr.io, for later uploading rootfs to ghcr.io
      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # GitHub username or org
          password: ${{ secrets.GITHUB_TOKEN }}    # GitHub actions builtin token. repo has to have pkg access.

      - name: Checkout build repo
        uses: actions/checkout@v3 # We don't need to clone git, really. A wget would suffice for GH-hosted runners. But using clone is better for Igor-hosted runners.
        with:
          repository: ${{ github.repository_owner }}/armbian-build
          ref: extensions
          fetch-depth: 1
          clean: false # true is default. it *will* delete the hosts /dev if mounted inside.

      - name: Build armbian-config
        id: armbian-config
        run: |
          bash ./compile.sh armbian-config SHARE_LOG=yes

      - name: Build armbian-zsh
        id: armbian-zsh
        run: |
          bash ./compile.sh armbian-zsh SHARE_LOG=yes

      - name: Build armbian-plymouth-theme
        id: armbian-plymouth-theme
        run: |
          bash ./compile.sh armbian-plymouth-theme SHARE_LOG=yes

      - name: Build fake_ubuntu_advantage_tools
        id: fake_ubuntu_advantage_tools
        run: |
          bash ./compile.sh fake-ubuntu-advantage-tools SHARE_LOG=yes

      - name: Build firmware (small)
        id: firmware
        run: |
          bash ./compile.sh firmware SHARE_LOG=yes

      - name: Build firmware (full)
        id: firmware_full
        run: |
          bash ./compile.sh firmware-full SHARE_LOG=yes
